name: markethub

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: markethub
      POSTGRES_PASSWORD: markethub
      POSTGRES_DB: markethub
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U markethub -d markethub']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ['redis-server', '--appendonly', 'no', '--save', '']
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '${MAILHOG_SMTP_PORT:-1025}:1025'
      - '${MAILHOG_UI_PORT:-8025}:8025'

volumes:
  pgdata:
